name: Six-Key
favicon: null
layout_spectrum: 0.0022503165528178215
typography_spectrum: 0.052524000871926546
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d140d'
    - '#7b5838'
    - '#e9c99f'
    - '#c5ac85'
    - '#fbeed7'
  brandStrength: 0.4375
  lightness: 0.3485431899316609
  saturation: 0.25
  rhythmicContrast: 0.3650410783011466
purpose: []
